config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :products
  resources :lists do
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find, only: %i[edit show update destroy]
  def index
    @lists = List.all
  end

  def edit
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @product_list = @list.products
  end

  def update
    @list.update(list_params)
    redirect_to root_path
  end

  def destroy
    @list.delete
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

  def find
    @list = List.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :find, only: %i[edit show update destroy]
  def index
    @products = Product.all
  end

  def edit
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def update
    @product.update(product_params)
    redirect_to root_path
  end

  def destroy
    @product.delete
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :list_id)
  end

  def find
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fastcontrol</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true%>
  </head>
  <body>
  <div class='banner'></div>
  <div class= 'main'>
  <div class = 'navbar'>
  <%= render 'shared/navbar' %>
  </div>
  <div class = 'products'>
    <%= yield %>
  </div>
  <div class = 'bill'>
   <%= render 'shared/bill' %>
   </div>
   </div>
  </body>

</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>
<div class ='cards'>
<% @lists.each do |list| %>
    <div class="card-product">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class="card-product-infos">
        <h2></h2> <br>
        <%= link_to list.title, list_path(list)%>
      </div>
    </div>
    <% end %>
</div>

app/views/lists/new.html.erb
<%= render 'shared/newlist' %>

app/views/lists/show.html.erb
<h2><%= @list.title %></h2>
<div class='cards'>
<% @product_list.each do |product| %>
    <div class="card-product">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class="card-product-infos">
        <h2>Name : <%= product.name %></h2> <br>
        <p>Price : <%= product.price %></p> <br>
        <button type="button" class="add-to-cart" data-id= <%=product.id%> data-name=<%=product.name%> data-price=<%=product.price%>>Ajouter au panier</button>
        <div class='card-infos_2'>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<div class ='cards'>
<% @products.each do |product| %>
    <div class="card-product">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class="card-product-infos">
        <h2>Name : <%= product.name %></h2> <br>
        <p>Price : <%= product.price %></p> <br>
        <div class='card-infos_2'>
        <div>
        <%= link_to 'Update', edit_product_path(product), method: :get %>
        </div>
        <div>
          <%= link_to 'Delete', product_path(product), method: :delete,
          data: { confirm: "Are you sure?" } %>
        </div>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

<%= render 'shared/newproduct' %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_bill.html.erb
<table class="table">
    <thead>
        <tr>
          <th> Article </th>
          <th> Prix </th>
          <th> Quantité </th>
          <th> Sous Total </th>
        </tr>
    </thead>
    <tbody id='article'>
    </tbody>
</table>

<p>Total : <span class="total">coucou </span>€</p>

<button id="confirm-command">Passer la commande</button>

app/views/shared/_navbar.html.erb
<%= link_to 'Accueil', root_path%>
<%= link_to 'Create Lists', new_list_path%>
<%= link_to 'Products', products_path%>
<%= link_to 'Create Products', new_product_path%>

app/views/shared/_newlist.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/shared/_newproduct.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.association :list, as: :radio_buttons%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>